Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: always_ignore

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
    EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Metrics/LineLength:
  Max: 120

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
