require: datarockets/style

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  Enabled: false

Layout/ArrayAlignmentExtended:
  Description: >-
                 Align the elements of an array literal if they span more than
                 one line.
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation
  IndentationWidth: ~

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/LineLength:
  Max: 120

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExponentialNotation:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true
  EnforcedStyle: no_braces

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
   Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NestedInterpolation:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
